M48
; DRILL file KiCad 10.0.6 date 2026-09-08T11:52:53
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2026-09-08T11:52:53+03:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,10.0.6
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C3.200
%
G90
G05
T1
X5.08Y-5.08
X5.08Y-121.92
X147.32Y-5.08
X147.32Y-121.92
M30
